version: "1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      DEBUG: 1
    command: gunicorn myfitroutine.wsgi --reload
  db:
    image: "postgres:11-alpine"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myfitroutine
    ports:
      - "5432:5432"

volumes:
  postgresql_data:
