# Generated by Django 4.0.7 on 2022-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_alter_workoutdiary_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdiary',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workoutdiary',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
